name: music
owner: rnateam
description: MUSIC is an algorithm for identification of enriched regions at multiple scales in the read depth signals from ChIP-Seq $
homepage_url: http://music.gersteinlab.org
type: unrestricted
categories:
- RNA
